/**
 * seed_dummy_files.js
 * 
 * Creates dummy physical files in uploads/submissions/ and inserts
 * 20-30 rows into every table in fyb_db.
 * 
 * Run: node scripts/seed_dummy_files.js
 */

const fs   = require('fs');
const path = require('path');
const pool = require('../src/config/db');

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Create a small dummy PDF-like text file and return its relative path */
function createDummyFile(folder, filename, content) {
    const dir = path.join(__dirname, '..', 'uploads', 'submissions', folder);
    fs.mkdirSync(dir, { recursive: true });
    const filePath = path.join(dir, filename);
    if (!fs.existsSync(filePath)) fs.writeFileSync(filePath, content);
    // Return path stored in DB – relative to project root, forward slashes
    return `uploads/submissions/${folder}/${filename}`;
}

/** Run a query, silently ignore duplicate-key errors */
async function safeInsert(conn, sql, params) {
    try {
        const [r] = await conn.query(sql, params);
        return r.insertId || null;
    } catch (e) {
        if (e.code === 'ER_DUP_ENTRY' || e.code === 'ER_DUP_KEY') return null;
        throw e;
    }
}

// ─── Dummy file content factory ──────────────────────────────────────────────

function makePdfContent(title, group, version) {
    return `%PDF-1.4 (dummy)
Title: ${title}
Group: ${group}
Version: ${version}
Date: ${new Date().toISOString()}

This is a dummy submission file generated by the seeder.
It simulates a real ${title} document submitted for the FYP portal.

Abstract:
This document presents the ${title} for the Final Year Project. The team has worked
diligently to complete all milestones on schedule. This file is stored locally at the
path recorded in the submission_file table in fyb_db.

Content would normally include methodology, design diagrams, test results, and references.
`;
}

// ─── Main seeder ─────────────────────────────────────────────────────────────

async function seed() {
    const conn = await pool.getConnection();
    console.log('✅ Connected to database');

    try {
        await conn.beginTransaction();

        // ── 1. Departments (already seeded, ensure extras) ──────────────────
        const deptExtras = [
            ['Artificial Intelligence', 'AI'],
            ['Cyber Security',          'CY'],
        ];
        for (const [name, code] of deptExtras) {
            await safeInsert(conn,
                'INSERT INTO department (DepartmentName, Code) VALUES (?, ?)',
                [name, code]);
        }
        console.log('  → departments OK');

        // Fetch all departments for later use
        const [depts] = await conn.query('SELECT DepartmentID FROM department');
        const deptIds = depts.map(d => d.DepartmentID);

        // ── 2. Batches ───────────────────────────────────────────────────────
        const batchData = [
            ['AI-2021',  2021, 2025, deptIds[4] || deptIds[0]],
            ['CS-2020',  2020, 2024, deptIds[0]],
            ['SE-2023',  2023, 2027, deptIds[1]],
            ['CY-2022',  2022, 2026, deptIds[4] || deptIds[0]],
            ['EE-2022',  2022, 2026, deptIds[2]],
        ];
        for (const [n, s, e, d] of batchData) {
            await safeInsert(conn,
                'INSERT INTO batch (BatchName, StartYear, EndYear, DepartmentID) VALUES (?, ?, ?, ?)',
                [n, s, e, d]);
        }
        console.log('  → batches OK');

        const [batches] = await conn.query('SELECT BatchID FROM batch');
        const batchIds = batches.map(b => b.BatchID);

        // ── 3. Extra persons (faculty + students) ────────────────────────────
        const extraPersons = [
            // [FirstName, LastName, Email, CNIC, Gender, DOB, PersonType]
            ['Zubair',   'Ahmed',   'zubair.ahmed@namal.edu.pk',    '35201-2100001-1', 'Male',   '1977-04-10', 'Faculty'],
            ['Hina',     'Baig',    'hina.baig@namal.edu.pk',       '35201-2100002-1', 'Female', '1983-08-15', 'Faculty'],
            ['Waqas',    'Siddiqui','waqas.siddiqui@namal.edu.pk',  '35201-2100003-1', 'Male',   '1980-12-22', 'Faculty'],
            ['Amina',    'Khalid',  'amina.khalid@external.org',    '35201-2100004-1', 'Female', '1975-03-07', 'Evaluator'],
            ['Rehan',    'Butt',    'rehan.butt@external.org',      '35201-2100005-1', 'Male',   '1968-11-30', 'Evaluator'],
            // Extra students (32-51)
            ['Talha',   'Baig',    'talha.baig@student.namal.edu.pk',     '35201-3000001-1','Male',  '2001-02-14','Student'],
            ['Sobia',   'Khan',    'sobia.khan@student.namal.edu.pk',     '35201-3000002-1','Female','2002-06-19','Student'],
            ['Adeel',   'Raza',    'adeel.raza@student.namal.edu.pk',     '35201-3000003-1','Male',  '2001-09-03','Student'],
            ['Maryam',  'Tariq',   'maryam.tariq@student.namal.edu.pk',   '35201-3000004-1','Female','2002-01-27','Student'],
            ['Junaid',  'Shah',    'junaid.shah@student.namal.edu.pk',    '35201-3000005-1','Male',  '2001-07-12','Student'],
            ['Iqra',    'Niazi',   'iqra.niazi@student.namal.edu.pk',     '35201-3000006-1','Female','2002-04-05','Student'],
            ['Ahsan',   'Malik',   'ahsan.malik@student.namal.edu.pk',    '35201-3000007-1','Male',  '2001-11-20','Student'],
            ['Nida',    'Hassan',  'nida.hassan@student.namal.edu.pk',    '35201-3000008-1','Female','2002-08-15','Student'],
            ['Fahad',   'Nawaz',   'fahad.nawaz@student.namal.edu.pk',    '35201-3000009-1','Male',  '2001-03-28','Student'],
            ['Zara',    'Butt',    'zara.butt@student.namal.edu.pk',      '35201-3000010-1','Female','2002-12-09','Student'],
            ['Shehzad', 'Alam',    'shehzad.alam@student.namal.edu.pk',   '35201-3000011-1','Male',  '2001-05-17','Student'],
            ['Aiman',   'Qureshi', 'aiman.qureshi@student.namal.edu.pk',  '35201-3000012-1','Female','2002-02-23','Student'],
            ['Noman',   'Fareed',  'noman.fareed@student.namal.edu.pk',   '35201-3000013-1','Male',  '2001-10-08','Student'],
            ['Rida',    'Shahid',  'rida.shahid@student.namal.edu.pk',    '35201-3000014-1','Female','2002-07-14','Student'],
            ['Asad',    'Gilani',  'asad.gilani@student.namal.edu.pk',    '35201-3000015-1','Male',  '2001-01-31','Student'],
        ];

        const newPersonIds = [];
        for (const [fn, ln, em, cn, g, d, pt] of extraPersons) {
            const id = await safeInsert(conn,
                'INSERT INTO person (FirstName, LastName, Email, CNIC, Gender, DOB, PersonType) VALUES (?,?,?,?,?,?,?)',
                [fn, ln, em, cn, g, d, pt]);
            if (id) newPersonIds.push({ id, pt, fn, ln, em });
        }
        console.log('  → extra persons OK');

        // ── 4. Extra faculty ─────────────────────────────────────────────────
        const [facPersons] = await conn.query(
            "SELECT p.PersonID FROM person p LEFT JOIN faculty f ON p.PersonID=f.FacultyID WHERE p.PersonType='Faculty' AND f.FacultyID IS NULL"
        );
        let empNo = 10;
        for (const fp of facPersons) {
            empNo++;
            await safeInsert(conn,
                'INSERT INTO faculty (FacultyID, EmployeeNo, Designation, DepartmentID) VALUES (?,?,?,?)',
                [fp.PersonID, `EMP-0${empNo}`, 'Lecturer', deptIds[empNo % deptIds.length]]);
        }
        console.log('  → extra faculty OK');

        // ── 5. Extra evaluators ──────────────────────────────────────────────
        const [evalPersons] = await conn.query(
            "SELECT p.PersonID FROM person p LEFT JOIN evaluators e ON p.PersonID=e.PersonID WHERE p.PersonType='Evaluator' AND e.PersonID IS NULL"
        );
        for (const ep of evalPersons) {
            await safeInsert(conn,
                "INSERT INTO evaluators (PersonID, EvaluatorType, Affiliation) VALUES (?, 'External', 'Guest University')",
                [ep.PersonID]);
        }
        console.log('  → extra evaluators OK');

        // ── 6. Extra students ─────────────────────────────────────────────────
        const [stuPersons] = await conn.query(
            "SELECT p.PersonID, p.FirstName FROM person p LEFT JOIN student s ON p.PersonID=s.StudentID WHERE p.PersonType='Student' AND s.StudentID IS NULL"
        );
        let regCounter = 100;
        for (const sp of stuPersons) {
            regCounter++;
            await safeInsert(conn,
                'INSERT INTO student (StudentID, RegistrationNo, BatchID) VALUES (?,?,?)',
                [sp.PersonID, `EX-${regCounter}`, batchIds[regCounter % batchIds.length]]);
        }
        console.log('  → extra students OK');

        // ── 7. Extra projects ─────────────────────────────────────────────────
        const extraProjects = [
            ['Deep Fake Detection System',       'CNN-based video forgery detection.',       'Computer Vision',   'Active'],
            ['Telemedicine Platform',             'Video consultation system for rural areas.','Healthcare IT',    'Active'],
            ['Supply Chain Blockchain',           'End-to-end supply chain transparency.',    'Blockchain',        'Active'],
            ['Student Performance Predictor',    'ML model for academic outcome prediction.', 'Machine Learning',  'Active'],
            ['Smart Parking System',              'IoT-based real-time parking management.',  'IoT',               'Active'],
            ['Sign Language Translator',          'AI-powered ASL to text translation.',      'Artificial Intelligence','Active'],
            ['E-Learning Platform with AI Tutor', 'Adaptive learning using NLP chatbot.',     'Natural Language Processing','Proposal'],
            ['Secure Voting System',              'Blockchain-based e-voting solution.',       'Blockchain',        'Active'],
            ['Traffic Management System',         'Computer vision for traffic flow control.','Computer Vision',   'Active'],
            ['Mental Health Chatbot',             'NLP-powered mental health support bot.',   'Natural Language Processing','Active'],
        ];
        const newProjectIds = [];
        for (const [t, d, dom, st] of extraProjects) {
            const id = await safeInsert(conn,
                'INSERT INTO project (Title, Description, Domain, ProjectStatus) VALUES (?,?,?,?)',
                [t, d, dom, st]);
            if (id) newProjectIds.push(id);
        }
        console.log('  → extra projects OK');

        // ── 8. Extra groups & student assignment ─────────────────────────────
        const [freeStudents] = await conn.query(
            'SELECT StudentID FROM student WHERE GroupID IS NULL ORDER BY StudentID LIMIT 30'
        );
        const [allProjects]  = await conn.query('SELECT ProjectID FROM project ORDER BY ProjectID');
        const [coordinator]  = await conn.query(
            "SELECT p.PersonID FROM person p WHERE p.PersonType='Coordinator' LIMIT 1"
        );
        const coordId = coordinator[0]?.PersonID || 2;

        const newGroupIds = [];
        for (let i = 0; i + 1 < freeStudents.length && i < 30; i += 2) {
            const gName   = `GRP-EX-${String(Math.floor(i/2)+1).padStart(2,'0')}`;
            const projId  = allProjects[(i/2) % allProjects.length].ProjectID;
            const gId = await safeInsert(conn,
                'INSERT INTO `groups` (GroupName, CoordinatorID, ProjectID) VALUES (?,?,?)',
                [gName, coordId, projId]);
            if (gId) {
                newGroupIds.push(gId);
                await conn.query('UPDATE student SET GroupID=? WHERE StudentID=?',
                    [gId, freeStudents[i].StudentID]);
                await conn.query('UPDATE student SET GroupID=? WHERE StudentID=?',
                    [gId, freeStudents[i+1].StudentID]);
            }
        }
        console.log('  → extra groups OK');

        // ── 9. More supervision assignments ──────────────────────────────────
        const [allFaculty]   = await conn.query('SELECT FacultyID FROM faculty');
        const [allProjectsForSup] = await conn.query(
            'SELECT p.ProjectID FROM project p LEFT JOIN project_supervision ps ON p.ProjectID=ps.ProjectID AND ps.Role="Supervisor" WHERE ps.SupervisionID IS NULL'
        );
        for (let i = 0; i < allProjectsForSup.length; i++) {
            const fac = allFaculty[i % allFaculty.length].FacultyID;
            await safeInsert(conn,
                "INSERT INTO project_supervision (ProjectID, FacultyID, Role) VALUES (?,?,'Supervisor')",
                [allProjectsForSup[i].ProjectID, fac]);
        }
        console.log('  → extra supervision OK');

        // ── 10. Extra milestones ──────────────────────────────────────────────
        const msData = [
            ['SE-2021', 'Project Proposal',   '2024-10-20', 10, 'Completed'],
            ['SE-2021', 'Literature Review',  '2025-01-15', 15, 'Completed'],
            ['SE-2021', 'Prototype Demo',     '2025-03-30', 25, 'Active'],
            ['SE-2021', 'Final Report',       '2025-06-20', 30, 'Upcoming'],
            ['SE-2021', 'Final Defense',      '2025-07-10', 20, 'Upcoming'],
            ['CS-2022', 'Prototype Demo',     '2025-09-01', 25, 'Upcoming'],
            ['AI-2021', 'Project Proposal',   '2024-11-01', 10, 'Completed'],
            ['AI-2021', 'System Design',      '2025-02-01', 20, 'Completed'],
            ['AI-2021', 'Implementation',     '2025-05-01', 30, 'Active'],
            ['AI-2021', 'Final Defense',      '2025-07-20', 20, 'Upcoming'],
        ];
        for (const [bname, title, due, w, st] of msData) {
            const [b] = await conn.query('SELECT BatchID FROM batch WHERE BatchName=?', [bname]);
            if (b.length > 0) {
                await safeInsert(conn,
                    'INSERT INTO milestone (BatchID, Title, DueDate, Weightage, Status) VALUES (?,?,?,?,?)',
                    [b[0].BatchID, title, due, w, st]);
            }
        }
        console.log('  → extra milestones OK');

        // ── 11. Submissions + dummy physical files ────────────────────────────
        const [allGroups]     = await conn.query('SELECT GroupID, ProjectID FROM `groups` WHERE ProjectID IS NOT NULL');
        const [activeMilestones] = await conn.query(
            "SELECT MilestoneID, Title FROM milestone WHERE Status IN ('Active','Completed')"
        );

        if (activeMilestones.length === 0) {
            console.warn('  ⚠ No active milestones found – skipping submissions');
        } else {
            const subTypes = ['Document', 'Code', 'Presentation', 'Zip File'];
            const statuses = ['Reviewed', 'Reviewed', 'Submitted', 'Late_Submission'];
            let subCount = 0;

            for (let i = 0; i < allGroups.length && subCount < 30; i++) {
                const grp = allGroups[i];
                const ms  = activeMilestones[i % activeMilestones.length];
                const typ = subTypes[i % subTypes.length];
                const sts = statuses[i % statuses.length];

                // Count existing subs for versioning
                const [[{ cnt }]] = await conn.query(
                    'SELECT COUNT(*) AS cnt FROM submission WHERE ProjectID=? AND MilestoneID=?',
                    [grp.ProjectID, ms.MilestoneID]);
                const version = `v${cnt + 1}.0`;

                // Skip trigger conflict: only insert if milestone is 'Active' or 'Completed'
                // We bypass the trigger by using direct INSERT with known-good data
                let subId = null;
                try {
                    const [sr] = await conn.query(
                        `INSERT INTO submission (ProjectID, MilestoneID, SubmissionVersion, SubmissionType, Status, SubmittedAt)
                         VALUES (?,?,?,?,?,NOW())`,
                        [grp.ProjectID, ms.MilestoneID, version, typ, sts]);
                    subId = sr.insertId;
                    subCount++;
                } catch (e) {
                    // Trigger may block – skip silently
                    continue;
                }

                // Create dummy file
                const ext      = typ === 'Code' ? 'zip' : typ === 'Presentation' ? 'pptx' : typ === 'Zip File' ? 'zip' : 'pdf';
                const folder   = typ === 'Document' || typ === 'Presentation' ? 'reports' : typ === 'Code' ? 'code' : 'proposals';
                const fname    = `${Date.now()}-grp${grp.GroupID}-${ms.MilestoneID}.${ext}`;
                const filePath = createDummyFile(folder, fname,
                    makePdfContent(ms.Title, `Group-${grp.GroupID}`, version));
                const fileSize = fs.statSync(path.join(__dirname, '..', filePath)).size;
                const mime     = ext === 'pdf' ? 'application/pdf' : ext === 'zip' ? 'application/zip' : 'application/vnd.ms-powerpoint';

                await safeInsert(conn,
                    'INSERT INTO submission_file (SubmissionID, FileName, FilePath, FileType, FileSize) VALUES (?,?,?,?,?)',
                    [subId, fname, filePath, mime, fileSize]);
            }
            console.log(`  → ${subCount} new submissions + files OK`);
        }

        // ── 12. More feedback ────────────────────────────────────────────────
        const [reviewedSubs] = await conn.query(
            "SELECT s.SubmissionID, ps.FacultyID FROM submission s JOIN project_supervision ps ON s.ProjectID=ps.ProjectID WHERE s.Status='Reviewed' AND ps.Role='Supervisor' LIMIT 25"
        );
        const fbComments = [
            ['Good work overall. Ensure all diagrams are labeled.', 'Approved'],
            ['References need IEEE format. Revise section 3.',       'Revision Required'],
            ['Excellent implementation. Prepare for final demo.',    'Approved'],
            ['Problem statement needs clearer scope definition.',    'Revision Required'],
            ['Test coverage is below 70%. Add unit tests.',          'Revision Required'],
            ['Well-structured report. Minor grammar issues found.',  'Approved'],
            ['UI is clean and responsive. Backend needs caching.',   'Approved'],
            ['Abstract too vague. Quantify your results.',           'Revision Required'],
            ['Good progress since last submission.',                  'Approved'],
            ['Code comments missing. Add JSDoc or Javadoc.',         'Revision Required'],
        ];
        let fbCount = 0;
        for (const rs of reviewedSubs) {
            const [cm, ft] = fbComments[fbCount % fbComments.length];
            await safeInsert(conn,
                'INSERT INTO feedback (SubmissionID, FacultyID, Comment, FeedbackType, FeedbackDate) VALUES (?,?,?,?,CURDATE())',
                [rs.SubmissionID, rs.FacultyID, cm, ft]);
            fbCount++;
        }
        console.log(`  → ${fbCount} feedback entries OK`);

        // ── 13. Extra evaluations ─────────────────────────────────────────────
        const [groupsForEval] = await conn.query(
            'SELECT GroupID FROM `groups` WHERE ProjectID IS NOT NULL LIMIT 20'
        );
        const [msList] = await conn.query('SELECT MilestoneID FROM milestone LIMIT 10');
        const evalDates = [
            '2025-05-10','2025-05-12','2025-05-14','2025-05-16','2025-05-18',
            '2025-05-20','2025-05-22','2025-05-24','2025-05-26','2025-05-28',
        ];
        const newEvalIds = [];
        for (let i = 0; i < Math.min(groupsForEval.length, 20); i++) {
            const ms = msList[i % msList.length];
            const id = await safeInsert(conn,
                "INSERT INTO evaluation (MilestoneID, GroupID, EvaluationDate, Status) VALUES (?,?,?,'Scheduled')",
                [ms.MilestoneID, groupsForEval[i].GroupID, evalDates[i % evalDates.length]]);
            if (id) newEvalIds.push(id);
        }
        console.log(`  → ${newEvalIds.length} extra evaluations OK`);

        // ── 14. Evaluation assignments for new evals ──────────────────────────
        const [allEvaluators] = await conn.query('SELECT EvaluatorID FROM evaluators');
        for (let i = 0; i < newEvalIds.length; i++) {
            const ev = allEvaluators[i % allEvaluators.length];
            await safeInsert(conn,
                "INSERT INTO evaluation_assignment (EvaluationID, EvaluatorID, EvaluatorRole, AssignedDate) VALUES (?,?,'Internal Evaluator',CURDATE())",
                [newEvalIds[i], ev.EvaluatorID]);
        }
        console.log('  → evaluation assignments OK');

        // ── 15. Evaluation criteria for new evals ────────────────────────────
        const criteriaTemplates = [
            ['Problem Statement Clarity',   10, 'How clearly the problem is defined'],
            ['Technical Implementation',    25, 'Quality and completeness of the solution'],
            ['Presentation Skills',         15, 'Communication and delivery quality'],
            ['Innovation & Originality',    20, 'Novelty of the approach'],
            ['Documentation Quality',       15, 'Completeness and clarity of written report'],
            ['Project Management',          15, 'Timeline adherence and work distribution'],
        ];
        for (let i = 0; i < newEvalIds.length; i++) {
            // Assign 2-3 criteria per evaluation
            const subset = criteriaTemplates.slice(i % 3, (i % 3) + 3);
            for (const [cn, mx, desc] of subset) {
                await safeInsert(conn,
                    'INSERT INTO evaluation_criteria (EvaluationID, CriteriaName, MaxMarks, Description) VALUES (?,?,?,?)',
                    [newEvalIds[i], cn, mx, desc]);
            }
        }
        console.log('  → evaluation criteria OK');

        // ── 16. User accounts for new persons ────────────────────────────────
        const [unaccouted] = await conn.query(
            'SELECT p.PersonID, p.Email, p.PersonType FROM person p LEFT JOIN user_account ua ON p.PersonID=ua.PersonID WHERE ua.PersonID IS NULL'
        );
        for (const up of unaccouted) {
            const uname = up.Email.split('@')[0].toLowerCase().replace(/[^a-z0-9.]/g,'');
            // Plain-text password (seeder only — auth controller accepts plain text)
            const pw = `pass_${up.PersonID}_2026`;
            await safeInsert(conn,
                "INSERT INTO user_account (Username, Password, Status, PersonID) VALUES (?,?,'Active',?)",
                [uname, pw, up.PersonID]);
        }
        // Assign roles
        const [newAccounts] = await conn.query(
            'SELECT ua.AccountID, p.PersonType FROM user_account ua JOIN person p ON ua.PersonID=p.PersonID LEFT JOIN useraccount_role ur ON ua.AccountID=ur.AccountID WHERE ur.AccountID IS NULL'
        );
        const roleMap = { Student: 1, Faculty: 2, Coordinator: 3, Admin: 4, Evaluator: 2 };
        for (const na of newAccounts) {
            const rid = roleMap[na.PersonType] || 1;
            await safeInsert(conn,
                'INSERT INTO useraccount_role (AccountID, RoleID) VALUES (?,?)',
                [na.AccountID, rid]);
        }
        console.log('  → user accounts OK');

        // ── 17. Audit log entries ─────────────────────────────────────────────
        const auditEntries = [
            ['user_account',  5,  'UPDATE', 'superadmin', 'Status: Active',     'Status: Suspended'],
            ['user_account',  5,  'UPDATE', 'superadmin', 'Status: Suspended',  'Status: Active'],
            ['project',       6,  'UPDATE', 'coordinator','Status: Proposal',   'Status: Active'],
            ['milestone',     4,  'UPDATE', 'coordinator','Status: Upcoming',   'Status: Active'],
            ['person',       31,  'INSERT', 'coordinator', null,                'New student added'],
            ['submission',    1,  'UPDATE', 'faculty',    'Status: Submitted',  'Status: Reviewed'],
            ['evaluation',    3,  'UPDATE', 'evaluator',  'Status: Scheduled',  'Status: Completed'],
            ['project',       2,  'UPDATE', 'coordinator','Status: Active',     'Status: Completed'],
            ['feedback',      1,  'INSERT', 'faculty',     null,                'Feedback added for submission 1'],
            ['user_account', 15,  'UPDATE', 'superadmin', 'Status: Active',     'Status: Inactive'],
        ];
        for (const [tbl, rid, act, by, old_, new_] of auditEntries) {
            await safeInsert(conn,
                'INSERT INTO audit_log (TableName, RecordID, Action, ChangedBy, OldData, NewData) VALUES (?,?,?,?,?,?)',
                [tbl, rid, act, by, old_, new_]);
        }
        console.log('  → audit log entries OK');

        await conn.commit();
        console.log('\n✅ All seed data committed successfully!');

    } catch (err) {
        await conn.rollback();
        console.error('\n❌ Seed failed, rolled back:', err.message);
        throw err;
    } finally {
        conn.release();
        await pool.end();
        console.log('   DB pool closed.');
    }
}

seed().catch(err => {
    console.error(err);
    process.exit(1);
});
